Achydra 758 featured searches
cul/ac-academiccommons pull request #244
Opened 2021-03-15 18:44 UTC by barmintor

2021-03-16 21:37 UTC, elohanlon commented on app/assets/javascripts/read-more.js
> +  $('.featured-searches .featured-search .description').readmore({
This may not be a big deal, and I see from the Readmore.js documentation that the existing anchor tag usage is actually encouraged, but technically it's better to use a `<button>` rather than an anchor if you're not actually linking to a real link location / functional hash.  @edmadrid may have some accessibility-related thoughts about this too.

2021-03-16 21:39 UTC, barmintor commented on app/assets/javascripts/read-more.js
> +  $('.featured-searches .featured-search .description').readmore({
yes, especially because this is his implementation :-D

2021-03-16 21:42 UTC, elohanlon commented on app/controllers/admin/featured_searches_controller.rb
> +        flash[:success] = "Created!"
You know you've been doing too much js single-page-app stuff when you go, "oh right!  `flash`!  that's a thing!" 😄

2021-03-16 21:53 UTC, elohanlon commented on app/controllers/collections_controller.rb
> +    @category = send params[:category_id].to_sym
Using a `params` value to dynamically invoke a method with the same name feels less safe to me than the previous implementation where the value was just used as a key in the `collections_config` hash (though I do see that the `raise` line above offers protection).  The dynamic method call is also a little harder to follow because I didn't initially know what category_id values might be submitted by the user.  Out of curiosity, why go for this implementation rather than the previous one?

2021-03-16 21:56 UTC, barmintor commented on app/controllers/collections_controller.rb
> +    @category = send params[:category_id].to_sym
it was the smallest change that would allow me to add dynamic data to only one of the collections. I expect that the journals will be available as data soon, and series could eventually be, so this implementation will probably change again in the near future as more configurations are entered.

2021-03-16 21:59 UTC, elohanlon commented on app/controllers/collections_controller.rb
> +    @category = send params[:category_id].to_sym
👍

2021-03-16 22:04 UTC, elohanlon commented on config/routes.rb
> +    resources :featured_searches, only: [:index, :edit, :new, :update, :create, :destroy]
```suggestion
    resources :featured_searches, except: [:show]
```

2021-03-16 22:10 UTC, elohanlon commented on db/migrate/20210310154653_create_featured_searches.rb
> +      t.string :filter_value, null: false
Do you want an index on `filter_value` because you're doing a query later on that references this field?

2021-03-16 23:03 UTC, elohanlon requested changes
Looks great!  Just had a couple of minor suggestions.

2021-03-17 13:39 UTC, barmintor commented on config/routes.rb
> +    resources :featured_searches, only: [:index, :edit, :new, :update, :create, :destroy]
Oh, good catch - I actually used `except` originally and changed during debugging.

2021-03-17 13:40 UTC, barmintor commented on db/migrate/20210310154653_create_featured_searches.rb
> +      t.string :filter_value, null: false
Excellent point.

2021-03-17 14:13 UTC, edmadrid commented on app/assets/javascripts/read-more.js
> +  $('.featured-searches .featured-search .description').readmore({
buttons are for actions! I can't remember if I thought about accessibility at the time, but I think it felt weird to make something a button when it didn't _look_ like a button. but yeah, I think screen readers would prefer a button here. I think I should fold this into a separate accessibility upgrade?

2021-03-17 14:20 UTC, edmadrid commented on app/assets/stylesheets/partials/featured-searches.scss
> +  border-radius: 6px;
won't affect anything but this border-radius can be removed. i think i was experimenting with borders at the time.

2021-03-17 14:27 UTC, edmadrid reviewed
I looked at the css and it looks good to me. I may need to revisit the styling for mobile screens if we remove the title fields and only include logos.

2021-05-06 14:15 UTC, merged